use_frameworks!

platform :ios, '10.0'

target 'AssentifySdk_Example' do
  pod 'AssentifySdk', :path => '../'

  target 'AssentifySdk_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
